### ISSUE TITLE
Installation doesn't pull in `attrs`

### ISSUE THREAD

**Issue by johnoshea** [sobolevn/flake8-eradicate#2]
Running `pipenv install --dev flake8-eradicate` gives the error message listed below (using the ale syntax checker inside vim). Adding `attrs` to the end of the install stanza has the plugin work as expected so it looks like it's not listed as a dependency?

```
 Traceback (most recent call last):
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 178, in load_plugin
-    self._load(verify_requirements)
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 150, in _load
-    self._plugin = resolve()
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2331, in resolve
-    module = __import__(self.module_name, fromlist=['__name__'], level=0)
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8_eradicate.py", line 6, in <module>
-    import attr
 ModuleNotFoundError: No module named 'attr'

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/bin/flake8", line 11, in <module>
-    sys.exit(main())
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
-    app.run(argv)
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/main/application.py", line 396, in run
-    self._run(argv)
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/main/application.py", line 383, in _run
-    self.initialize(argv)
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/main/application.py", line 365, in initialize
-    self.find_plugins()
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/main/application.py", line 191, in find_plugins
-    self.check_plugins.load_plugins()
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
-    plugins = list(self.manager.map(load_plugin))
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 311, in map
-    yield func(self.plugins[name], *args, **kwargs)
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
-    return plugin.load_plugin()
   File "/Users/johno/.local/share/virtualenvs/glint_processor-GwxykaLr/lib/python3.6/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
-    raise failed_to_load
 flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "E8" due to No module named 'attr'.
```

**Comment by sobolevn** [comment]
Oops, I had this patch in `master`, but I was not released. https://github.com/sobolevn/flake8-eradicate/commit/8def98692e435a8e6a09ab8f92facb3ef0e9811d

Now, it is released as `0.1.1.` Thanks for firing an issue!
