### ISSUE TITLE
Exception when running via pre-commit

### ISSUE THREAD

**Issue by uriva** [sobolevn/flake8-eradicate#76]
Hi, I ran this on my project through pre-commit flake8 hook and got this exception:

>Traceback (most recent call last):
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 397, in run
    self._run(argv)
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 384, in _run
    self.initialize(argv)
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 368, in initialize
    self.register_plugin_options()
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 209, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 490, in register_options
    list(self.manager.map(register_and_enable))
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 298, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 486, in register_and_enable
    call_register_options(plugin)
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 398, in generated_function
    return method(optmanager, *args, **kwargs)
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 217, in register_options
    add_options(optmanager)
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8_eradicate.py", line 67, in add_options
    parse_from_config=True,
  File "/home/uri/.cache/pre-commit/repo7r732xof/py_env-python3.7/lib/python3.7/site-packages/flake8/options/manager.py", line 395, in add_option
    self._current_group.add_argument(*option_args, **option_kwargs)
  File "/usr/lib/python3.7/argparse.py", line 1362, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'type'

**Comment by sobolevn** [comment]
Sorry, but it looks like `flake8` or `pre-commit` issue. I am pretty sure that it is not related.
